controllers:
    resource: ../src/Controller/
    type: attribute
index:
    path: /
    controller: App\Controller\LoginController::index
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
adminDashboard:
    path: /RhDashboard
    controller: App\Controller\DashboardController::index
employeMenu:
    path: /RH/empMenu
    controller: app\Controller\gestEmploye\empMenuController
listeEmploye:
    path: /RH/empMenu/listEmp
    controller: app\Controller\gestEmploye\EmpListeController
employeInfo:
    path: /RH/empMenu/listEmp/empInfo
    controller: app\Controller\gestEmploye\EmpInfoController
addEmploye:
    path: /RH/empMenu/addEmp
    controller: app\Controller\gestEmploye\addEmpController
absence:
    path: /RH/absence/absencemenu
    controller: app\Controller\absence\AbsenceController
absencePerso:
    path: /RH/absence/personnelAbsence
    controller: app\Controller\absence\AbsencePersonnelController
conge:
    path: /RH/conge/congemenu
    controller:  app\Controller\conge\CongeController

employeDashboard:
    path: /userDashboard
    controller: App\Controller\DashboardController