controllers:
    resource: ../src/Controller/
    type: attribute
index:
    path: /
    controller: App\Controller\LoginController::index
adminDashboard:
    path: /adminDashboard
    controller: App\Controller\DashboardController::index
employeMenu:
    path: /admin/empMenu
    controller: app\Controller\gestEmploye\empMenuController
listeEmploye:
    path: /admin/empMenu/listEmp
    controller: app\Controller\gestEmploye\EmpListeController
employeInfo:
    path: /admin/empMenu/listEmp/empInfo
    controller: app\Controller\gestEmploye\EmpInfoController
addEmploye:
    path: /admin/empMenu/addEmp
    controller: app\Controller\gestEmploye\addEmpController
absence:
    path: /admin/absence/absencemenu
    controller: app\Controller\absence\AbsenceController